version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: "no"
        hostname: app
        ports:
            - "__PORT__:8000"
        env_file: ./common.env
        links:
            - postgres:postgres
        depends_on:
            - postgres
        volumes:
            # __INSTALL_DIR__ -> /var/www/$app/
            - __INSTALL_DIR__/static/:/static/:rw
            - __INSTALL_DIR__/media/:/media/:rw
        entrypoint: /app/app-entrypoint.sh

    postgres:
        # https://hub.docker.com/_/postgres
        image: postgres:alpine
        restart: "no"
        hostname: postgres # same as "POSTGRES_HOST" in common.env
        ports:
            - "5432" # same as "POSTGRES_PORT" in common.env
        env_file: ./common.env
        volumes:
            # __DATA_DIR__ -> /home/yunohost.app/$app/
            - __DATA_DIR__/postgresql-data/:/var/lib/postgresql/data/:rw

    redis:
        # https://hub.docker.com/_/redis
        image: redis:alpine
        restart: "no"
        hostname: redis # same as "REDIS_HOST" in common.env
        ports:
            - "6379" # same as "REDIS_PORT" in common.env
        env_file: ./common.env
