version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: "no"
        hostname: app
        ports:
            - "__PORT__:8000"
        env_file: common.env
        links:
            - postgres:postgres
        depends_on:
            - postgres
        volumes:
            # __INSTALL_DIR__ -> /var/www/$app/
            - __INSTALL_DIR__/static/:/static/:rw
            - __INSTALL_DIR__/media/:/media/:rw
        entrypoint: /app/app-entrypoint.sh

    postgres:
        # https://hub.docker.com/_/postgres
        image: postgres:alpine
        restart: "no"
        hostname: postgres
        ports:
            - "5432"
        env_file: common.env
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - ./postgres-init.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
            #
            # __DATA_DIR__ -> /home/yunohost.app/$app/
            - __DATA_DIR__/postgresql-data/:/var/lib/postgresql/data/:rw


